# Generated by Django 3.0 on 2020-04-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='featured22',
        ),
    ]
