# Generated by Django 3.0 on 2020-05-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_featured22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
